- name: Initial deployment of pizzasuicideclub.com
  hosts: webservers
  remote_user: takosuke
  vars:
  - app_name: pizzasuicideclub.com
  - deploy_user: takosuke
  - domain_name: pizzasuicideclub.com
  - repo_path: "takosuke/psc"
  - repo_remote : origin
  - repo_version: master
  - webapps_dir: "/home/takosuke/public_html"
  - app_root: "html/psc"
  - static_root: "static"
  - media_root: "html/psc/media/uploads"  
  - wsgi_callable: application

#  vars_prompt:
  roles:
  - clone_repo
  - log_setup
  - nginx_setup
  - supervisord_setup
  - virtualenv_setup
  - pip_requirements
  - app_setup
