---

- name: Install Pillow prerequisites
  apt: name=python-imaging state=build-dep
  become: yes
  become_method: sudo

- name: Install app requirements
  pip:  requirements={{ webapps_dir }}/{{ app_name }}/html/requirements.txt
        virtualenv=/home/{{ deploy_user }}/.virtualenvs/{{ app_name }}
        #extra_args='--allow-external --allow-unverified'
        