# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField()),
                ('text', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('slug', models.CharField(max_length=150, null=True, unique=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='cover')),
            ],
        ),
    ]
