# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160517_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
